remote_theme: mmistakes/minimal-mistakes@4.27.1

plugins: 
  - jekyll-include-cache

include:
  - _pages

# Site settings
locale: "en-US"
title: "Batuhan Yeltekin"
title_separator: "-"
subtitle: ""
name: "Batuhan Yeltekin"
description: "Batuhan Yeltekin's Personal Portfolio Page"
url: "https://batuhanyeltekin.github.io"
baseurl: ""
repository: "batuhanyeltekin/batuhanyeltekin.github.io"

# Site Author
author:
  name: "Batuhan Yeltekin"
  avatar: "/assets/images/batuhan.png"
  bio: "Batuhan Yeltekin is rising junior at Columbia University studying Computer Science and Economics."
  location: "New York, NY"
  email: "batuhan.duru.yeltekin@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/batuhanyeltekin"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/batuhanyeltekin/"
    - label: "Photo Gallery"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/fotoyeltekin/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/batuhanyeltekin"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/batuhanyeltekin/"

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

# Main navigation
main:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Resume"
    url: /resume/

# Theme settings
minimal_mistakes_skin: "contrast"

# Build settings
markdown: kramdown
search: true

